INSERT INTO orb_setup_definitions (id, name, number, type, framework, grade, conditions, eval_logic,
  backtest_n,
  backtest_win_rate_5d, backtest_avg_return_5d,
  backtest_win_rate_10d, backtest_avg_return_10d,
  backtest_win_rate_20d, backtest_avg_return_20d,
  backtest_win_rate_60d, backtest_avg_return_60d,
  gauge_median_days, gauge_median_return, gauge_target_description, description) VALUES

-- BUY SETUPS
('smi-oversold-gauge', 'SMI Oversold Gauge', 1, 'buy', 'gauge-to-target', 'A',
 '["SMI crosses below -60", "Target: SMI recovers to +30"]', 'smi_oversold_gauge',
 19, NULL, NULL, NULL, NULL, 70.6, 7.25, NULL, NULL,
 11, 7.25, 'SMI recovers to +30',
 'When daily SMI plunges below -60, momentum is deeply oversold. Track until SMI recovers to +30.'),

('oversold-extreme', 'Oversold Extreme', 2, 'buy', 'fixed-horizon', 'S',
 '["Price >40% below 200-day SMA"]', 'oversold_extreme',
 8, 75.0, 6.41, 87.5, 11.04, 87.5, 14.79, 100.0, 51.59,
 NULL, NULL, NULL,
 'Generational buying opportunity. Dec 2022 territory. Override everything.'),

('regime-shift', 'Regime Shift', 3, 'buy', 'fixed-horizon', 'A+',
 '["Weekly BX LL->HL transition", "Price above Weekly 13 EMA"]', 'regime_shift',
 19, 78.9, 3.59, 89.5, 5.20, 84.2, 5.38, 46.7, 6.90,
 NULL, NULL, NULL,
 'Weekly momentum turns positive AND price reclaims structure. The correction is over.'),

('deep-value', 'Deep Value Bounce', 4, 'buy', 'fixed-horizon', 'A+',
 '["200 SMA -20% to -10%", "Daily BX in HL state"]', 'deep_value_bounce',
 17, 64.7, 2.20, 82.4, 5.42, 82.4, 9.65, 58.8, 10.86,
 NULL, NULL, NULL,
 'Selling exhausted in structurally oversold territory. BX HL confirms the turn.'),

('green-shoots', 'Green Shoots (Oversold)', 5, 'buy', 'fixed-horizon', 'A',
 '["Daily BX transitions LL->HL", "Price below 200-day SMA"]', 'green_shoots',
 18, 55.6, 1.58, 72.2, 5.88, 72.2, 8.18, 66.7, 17.34,
 NULL, NULL, NULL,
 'Momentum turns positive while structurally oversold. Only works below the 200 SMA.'),

('momentum-flip', 'Momentum Flip', 6, 'buy', 'fixed-horizon', 'A',
 '["Daily BX transitions HL->HH", "RSI below 55"]', 'momentum_flip',
 13, 61.5, 1.22, 69.2, 2.35, 69.2, 2.35, 75.0, 23.35,
 NULL, NULL, NULL,
 'Trend just confirmed positive with room to run. Often marks start of multi-week moves.'),

('trend-confirm', 'Trend Confirmation', 7, 'buy', 'fixed-horizon', 'A-',
 '["SMI bull cross (above signal line)", "Daily BX in HH state"]', 'trend_confirmation',
 31, 54.8, 0.71, 58.1, 3.98, 67.7, 9.22, 72.4, 13.23,
 NULL, NULL, NULL,
 'Both momentum indicators agree bullish conditions are in effect. Workhorse trend signal.'),

('trend-ride', 'Daily Trend Ride', 8, 'buy', 'fixed-horizon', 'B+',
 '["Daily BX HH", "Price above Daily 21 EMA", "Price above Weekly 21 EMA"]', 'trend_ride',
 154, 50.6, 0.88, 55.8, 2.44, 59.7, 4.27, 59.9, 9.43,
 NULL, NULL, NULL,
 'Trend intact across timeframes. Highest frequency signal - the bread-and-butter.'),

('trend-continuation', 'Trend Continuation', 9, 'buy', 'fixed-horizon', 'B+',
 '["Weekly EMAs stacked (9>13>21)", "Price above all weekly EMAs", "Daily BX HH"]', 'trend_continuation',
 118, 50.0, 0.82, 52.5, 2.19, 56.8, 3.25, 63.2, 10.90,
 NULL, NULL, NULL,
 'Full weekly structure confirmed healthy + daily momentum positive.'),

('goldilocks', 'Goldilocks Zone', 10, 'buy', 'fixed-horizon', 'A+',
 '["RSI 45-65", "SMI 0 to 40", "Daily BX HH"]', 'goldilocks',
 40, 50.0, 2.43, 65.0, 7.40, 72.5, 11.80, 87.2, 23.89,
 NULL, NULL, NULL,
 'All indicators agree trend is confirmed, positive, and has room to run. Sweet spot before the crowd arrives.'),

('capitulation', 'Capitulation Bounce', 11, 'buy', 'fixed-horizon', 'A',
 '["4+ consecutive down days", "RSI below 40"]', 'capitulation_bounce',
 18, 72.2, 6.94, 61.1, 5.84, 64.7, 11.94, 64.7, 28.03,
 NULL, NULL, NULL,
 'Panic selling exhausted. 72% win rate at 5 days - best short-term bounce signal.'),

-- AVOID SETUPS
('smi-overbought', 'SMI Overbought Gauge', 1, 'avoid', 'gauge-to-target', 'AVOID',
 '["SMI crosses above +75"]', 'smi_overbought_gauge',
 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 17, -3.67, 'SMI falls to -30',
 '75% of the time, by the time SMI resets, price is lower. Trim calls.'),

('dual-ll', 'Dual Timeframe Downtrend', 2, 'avoid', 'fixed-horizon', 'AVOID',
 '["Daily BX in LL", "Weekly BX in LL"]', 'dual_ll',
 81, 43.2, -1.73, 45.5, -1.80, 41.7, -2.75, 41.5, 0.63,
 NULL, NULL, NULL,
 'Both timeframes aligned bearish. Consistently negative through 20d. Do not buy calls.'),

('overextended', 'Overextended', 3, 'avoid', 'fixed-horizon', 'AVOID',
 '["Price >25% above 200-day SMA"]', 'overextended',
 207, 40.6, -0.75, 43.5, -1.13, 37.7, -2.90, 28.2, -7.69,
 NULL, NULL, NULL,
 'Statistically worst zone for new call positions. 28% win rate at 60d.'),

('momentum-crack', 'Momentum Crack', 4, 'avoid', 'fixed-horizon', 'AVOID',
 '["SMI was above 50", "SMI lost 10+ points in 3 days"]', 'momentum_crack',
 24, 62.5, 3.44, 45.8, -0.92, 45.8, -0.78, 42.1, -2.14,
 NULL, NULL, NULL,
 'Rally momentum snapping. 5d bounce is a trap - damage comes at 10-60d.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  number = EXCLUDED.number,
  type = EXCLUDED.type,
  framework = EXCLUDED.framework,
  grade = EXCLUDED.grade,
  conditions = EXCLUDED.conditions,
  eval_logic = EXCLUDED.eval_logic,
  backtest_n = EXCLUDED.backtest_n,
  backtest_win_rate_5d = EXCLUDED.backtest_win_rate_5d,
  backtest_avg_return_5d = EXCLUDED.backtest_avg_return_5d,
  backtest_win_rate_10d = EXCLUDED.backtest_win_rate_10d,
  backtest_avg_return_10d = EXCLUDED.backtest_avg_return_10d,
  backtest_win_rate_20d = EXCLUDED.backtest_win_rate_20d,
  backtest_avg_return_20d = EXCLUDED.backtest_avg_return_20d,
  backtest_win_rate_60d = EXCLUDED.backtest_win_rate_60d,
  backtest_avg_return_60d = EXCLUDED.backtest_avg_return_60d,
  gauge_median_days = EXCLUDED.gauge_median_days,
  gauge_median_return = EXCLUDED.gauge_median_return,
  gauge_target_description = EXCLUDED.gauge_target_description,
  description = EXCLUDED.description;
