INSERT INTO orb_setup_definitions (
  id,
  name,
  number,
  type,
  framework,
  grade,
  conditions,
  eval_logic,
  public_name,
  one_liner,
  public_description,
  category_tags,
  backtest_n,
  backtest_win_rate_5d,
  backtest_avg_return_5d,
  backtest_win_rate_10d,
  backtest_avg_return_10d,
  backtest_win_rate_20d,
  backtest_avg_return_20d,
  risk_note,
  description
) VALUES (
  'vix-spike-reversal',
  'VIX Spike Reversal',
  12,
  'buy',
  'fixed-horizon',
  'B',
  '["VIX weekly change >= 30%"]',
  'vix_spike_reversal',
  'VIX Spike Reversal',
  'VIX spiked >=30% in a week - historically TSLA bounces with 67% win rate over 20 days',
  'When the VIX spikes 30% or more in a single week, fear is likely peaking. Over 12 occurrences since 2021, TSLA has averaged +2.8% over 20 trading days with a 67% win rate. This signal fires roughly 2-3 times per year.',
  ARRAY['volatility', 'mean-reversion'],
  12,
  58,
  1.64,
  58,
  1.68,
  67,
  2.82,
  'Not a buy-the-dip signal. The 200 SMA must hold. Oil/macro can override the statistical edge.',
  'When the VIX spikes 30% or more in a single week, fear is likely peaking. Over 12 occurrences since 2021, TSLA has averaged +2.8% over 20 trading days with a 67% win rate. This signal fires roughly 2-3 times per year.'
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  number = EXCLUDED.number,
  type = EXCLUDED.type,
  framework = EXCLUDED.framework,
  grade = EXCLUDED.grade,
  conditions = EXCLUDED.conditions,
  eval_logic = EXCLUDED.eval_logic,
  public_name = EXCLUDED.public_name,
  one_liner = EXCLUDED.one_liner,
  public_description = EXCLUDED.public_description,
  category_tags = EXCLUDED.category_tags,
  backtest_n = EXCLUDED.backtest_n,
  backtest_win_rate_5d = EXCLUDED.backtest_win_rate_5d,
  backtest_avg_return_5d = EXCLUDED.backtest_avg_return_5d,
  backtest_win_rate_10d = EXCLUDED.backtest_win_rate_10d,
  backtest_avg_return_10d = EXCLUDED.backtest_avg_return_10d,
  backtest_win_rate_20d = EXCLUDED.backtest_win_rate_20d,
  backtest_avg_return_20d = EXCLUDED.backtest_avg_return_20d,
  risk_note = EXCLUDED.risk_note,
  description = EXCLUDED.description;
