export type BacklogStatus = "backlog" | "in-progress" | "done";
export type BacklogPriority = "P0" | "P1" | "P2";
export type BacklogCategory = "growth" | "workflow" | "platform";

export interface BacklogItem {
  id: string;
  priority: BacklogPriority;
  title: string;
  description: string;
  status: BacklogStatus;
  category: BacklogCategory;
  tags: string[];
  dateAdded: string;
  effort: "quick" | "medium" | "large";
  assessment: string;
  rating: string;
  isNew?: boolean;
}

export interface BackloggedItem {
  id: string;
  title: string;
  originalGoal: string;
  whyBacklogged: string;
  rating: string;
}

export const categories = {
  growth: {
    emoji: "🎯",
    title: "GOAL 1: Grow Subscribers",
    description: "Convert X impressions → followers → email signups → paying members",
  },
  workflow: {
    emoji: "⚡",
    title: "GOAL 2: Streamline Workflows",
    description: "Automate repetitive tasks → free up Justin's time for high-leverage work",
  },
  platform: {
    emoji: "🏗️",
    title: "GOAL 3: Platform Excellence",
    description: "Flawless operations + features that create massive subscriber value",
  },
};

export const backlogItems: BacklogItem[] = [
  // ============ GOAL 1: GROW SUBSCRIBERS (12 items) ============
  {
    id: "daily-mode-card",
    priority: "P0",
    title: "Daily Mode Card",
    description: "Branded image posted 7:45am CT daily with MODE, key levels, posture. Template-based, auto-generated from report data.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Automation", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Compounds daily. Zero-effort once templated. Becomes ritual. Brand building 101.",
  },
  {
    id: "hiro-spike-alerts-delayed",
    priority: "P0",
    title: "HIRO Spike Alerts (Delayed)",
    description: "Post HIRO threshold alerts to X with 15-30 min delay. Creates FOMO, proves edge.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "FOMO", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "FOMO is the strongest conversion driver. 'Subscribers got this 30 min ago' = immediate value proof.",
  },
  {
    id: "base-case-accuracy-posts",
    priority: "P0",
    title: "Base Case Accuracy Posts",
    description: "Screenshot report predictions vs actual results. Builds credibility with proof.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Proof", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Proof beats promises. Screenshot predictions vs results. Undeniable credibility.",
  },
  {
    id: "weekly-scorecard-thread",
    priority: "P0",
    title: "Weekly Scorecard Thread",
    description: "Friday/Saturday thread: predictions vs results, accuracy %, lessons. Accountability builds trust.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Transparency", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Radical transparency is RARE. Showing losses builds more trust than hiding them. Differentiator.",
  },
  {
    id: "free-daily-levels-email",
    priority: "P0",
    title: "Free Daily Levels Email (Lead Magnet)",
    description: "Exchange email for free daily key levels. Builds list. Nurtures to paid.",
    status: "backlog",
    category: "growth",
    tags: ["Email", "Lead Gen", "Funnel"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "MISSING FROM CURRENT STRATEGY. Exchange email for free daily key levels. Builds list. Nurtures to paid. This is the funnel gap.",
    isNew: true,
  },
  {
    id: "why-it-moved-recaps",
    priority: "P1",
    title: '"Why It Moved" Recaps',
    description: 'After big moves (±3%), explain what happened with levels/HIRO. Educational authority.',
    status: "backlog",
    category: "growth",
    tags: ["Content", "Education", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "Captures search traffic ('why did TSLA drop'). Positions as expert, not reactor. Evergreen.",
  },
  {
    id: "public-accuracy-dashboard",
    priority: "P0",
    title: "Public Accuracy Dashboard Link",
    description: "Every post links to flacko.ai/accuracy showing historical track record. Social proof at scale.",
    status: "backlog",
    category: "growth",
    tags: ["Website", "Proof", "Trust"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Every post links to flacko.ai/accuracy showing historical track record. Social proof at scale. 'Don't trust me, check the numbers.'",
    isNew: true,
  },
  {
    id: "pre-earnings-playbook",
    priority: "P1",
    title: "Pre-Earnings Playbook",
    description: "3-5 days before ER: historical moves, gamma setup, scenarios. Peak attention.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Earnings", "X"],
    dateAdded: "2026-02-02",
    effort: "large",
    rating: "⭐⭐⭐⭐",
    assessment: "Peak attention moments. Only 4x/year but MASSIVE reach. Worth the effort.",
  },
  {
    id: "what-would-you-do-polls",
    priority: "P1",
    title: '"What Would You Do?" Polls',
    description: "Engagement bait that educates. 'TSLA at $430, HIRO +800M. You: A) Buy B) Wait C) Sell'",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Engagement", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐",
    assessment: "Engagement bait that educates. 'TSLA at $430, HIRO +800M. You: A) Buy B) Wait C) Sell' — drives comments, shares framework.",
    isNew: true,
  },
  {
    id: "contrarian-call-accountability",
    priority: "P2",
    title: "Contrarian Call + Accountability",
    description: "High-conviction public calls with specific targets. Engagement + credibility if right.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Bold", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "High risk/reward. When right = viral. When wrong = own it = trust. Use sparingly.",
  },
  {
    id: "subscriber-testimonials",
    priority: "P2",
    title: "Subscriber Testimonial Highlights",
    description: "Screenshot subscriber wins. 'Member caught the $424 bounce using our levels.'",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Social Proof", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐",
    assessment: "Screenshot subscriber wins. 'Member caught the $424 bounce using our levels.' Real people, real results.",
    isNew: true,
  },
  {
    id: "loss-autopsy-posts",
    priority: "P2",
    title: "Loss Autopsy Posts",
    description: "When a call is WRONG, publicly break down why. Counter-intuitive but builds massive trust.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Transparency", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "When a call is WRONG, publicly break down why. Counter-intuitive but builds massive trust. Nobody does this.",
    isNew: true,
  },

  // ============ GOAL 2: STREAMLINE WORKFLOWS (7 items) ============
  {
    id: "weekly-report-template",
    priority: "P0",
    title: "Weekly Report Template",
    description: "Create .md template for Sunday weekly workflow.",
    status: "done",
    category: "workflow",
    tags: ["Template", "Reports", "Blocking"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "BLOCKING. Can't do Sunday workflow without it. Immediate unblock.",
  },
  {
    id: "daily-mode-card-generator",
    priority: "P0",
    title: "Daily Mode Card Generator",
    description: "Input: report JSON → Output: branded PNG. Post in 30 seconds.",
    status: "in-progress",
    category: "workflow",
    tags: ["Automation", "Design", "Pipeline"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Input: report JSON → Output: branded PNG. Post in 30 seconds. Enables #1 growth item.",
  },
  {
    id: "accuracy-comparison-generator",
    priority: "P0",
    title: "Accuracy Comparison Generator",
    description: "Input: predictions + actuals → Output: before/after image. Enables accuracy posts without manual work.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Design", "Pipeline"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Input: predictions + actuals → Output: before/after image. Enables accuracy posts without manual work.",
  },
  {
    id: "report-to-tweet-pipeline",
    priority: "P0",
    title: "Report-to-Tweet Pipeline",
    description: "Auto-generate 3-5 tweet drafts from each daily report. Pick best, post. Eliminates blank page problem.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Content", "AI"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "NEW. Auto-generate 3-5 tweet drafts from each daily report. Pick best, post. Eliminates blank page problem.",
    isNew: true,
  },
  {
    id: "auto-screenshot-scheduler",
    priority: "P1",
    title: "Auto-Screenshot Scheduler",
    description: "Capture TradingView/SpotGamma at market open, noon, close automatically. No manual intervention.",
    status: "done",
    category: "workflow",
    tags: ["Automation", "Screenshots", "Cron"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "Capture TradingView/SpotGamma at market open, noon, close automatically. No manual intervention.",
    isNew: true,
  },
  {
    id: "content-calendar-dashboard",
    priority: "P2",
    title: "Content Calendar Dashboard",
    description: "Visual calendar: what posts when. Never miss a scheduled post. See gaps. Plan ahead.",
    status: "backlog",
    category: "workflow",
    tags: ["Dashboard", "Planning", "Content"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "Visual calendar: what posts when. Never miss a scheduled post. See gaps. Plan ahead.",
    isNew: true,
  },
  {
    id: "one-click-post-queue",
    priority: "P2",
    title: "One-Click Post Queue",
    description: "Approve → auto-posts to X/Discord. No copy-paste. No manual webhook calls.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Publishing", "UX"],
    dateAdded: "2026-02-02",
    effort: "large",
    rating: "⭐⭐⭐⭐",
    assessment: "Approve → auto-posts to X/Discord. No copy-paste. No manual webhook calls.",
    isNew: true,
  },

  // ============ GOAL 3: PLATFORM EXCELLENCE (7 items) ============
  {
    id: "email-notifications-backend",
    priority: "P0",
    title: "Email Notifications Backend",
    description: "Build backend for price alert email delivery. Member-requested feature.",
    status: "backlog",
    category: "platform",
    tags: ["Email", "Alerts", "Backend"],
    dateAdded: "2026-02-02",
    effort: "large",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "Member-requested. Not everyone watches Discord. Direct delivery = direct value.",
  },
  {
    id: "alert-accuracy-tracking-auto",
    priority: "P0",
    title: "Alert Accuracy Tracking (Auto)",
    description: "System auto-tracks which price alerts hit. Display hit rate. Proves system works.",
    status: "backlog",
    category: "platform",
    tags: ["Analytics", "Alerts", "Trust"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "NEW. System auto-tracks which price alerts hit. Display hit rate. Proves system works.",
    isNew: true,
  },
  {
    id: "public-accuracy-page",
    priority: "P0",
    title: "Public Accuracy Page",
    description: "flacko.ai/accuracy — historical track record anyone can verify. Marketing + transparency.",
    status: "backlog",
    category: "platform",
    tags: ["Website", "Trust", "Marketing"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐⭐",
    assessment: "NEW. flacko.ai/accuracy — historical track record anyone can verify. Marketing + transparency.",
    isNew: true,
  },
  {
    id: "discord-feedback-channel",
    priority: "P1",
    title: "Discord Feedback Channel",
    description: "Dedicated channel for member ideas. Trunks monitors, easy engagement win.",
    status: "done",
    category: "platform",
    tags: ["Discord", "Community", "Feedback"],
    dateAdded: "2026-02-02",
    effort: "quick",
    rating: "⭐⭐⭐⭐",
    assessment: "10-minute setup. Immediate feedback loop. Know what subscribers actually want.",
  },
  {
    id: "mobile-push-notifications",
    priority: "P1",
    title: "Mobile Push Notifications",
    description: "Beyond email. Instant alerts to phone. Higher engagement than email.",
    status: "backlog",
    category: "platform",
    tags: ["Mobile", "Alerts", "Engagement"],
    dateAdded: "2026-02-02",
    effort: "large",
    rating: "⭐⭐⭐⭐",
    assessment: "Beyond email. Instant alerts to phone. Higher engagement than email.",
    isNew: true,
  },
  {
    id: "member-performance-dashboard",
    priority: "P2",
    title: "Member Performance Dashboard",
    description: "Personalized: their alerts, which ones hit, their accuracy following the system.",
    status: "backlog",
    category: "platform",
    tags: ["Dashboard", "Personalization", "Analytics"],
    dateAdded: "2026-02-02",
    effort: "large",
    rating: "⭐⭐⭐⭐",
    assessment: "Personalized: their alerts, which ones hit, their accuracy following the system.",
    isNew: true,
  },
  {
    id: "spotgamma-data-expansion",
    priority: "P2",
    title: "SpotGamma Data Expansion",
    description: "Add Equity Hub levels, FlowPatrol insights to daily reports. More data = more value.",
    status: "in-progress",
    category: "platform",
    tags: ["Data", "Reports", "SpotGamma"],
    dateAdded: "2026-02-02",
    effort: "medium",
    rating: "⭐⭐⭐⭐",
    assessment: "Specific: Add Equity Hub levels, FlowPatrol insights to daily reports. More data = more value.",
    isNew: true,
  },
];

// Backlogged items (weak ideas moved to storage)
export const backloggedItems: BackloggedItem[] = [
  {
    id: "monday-preview-posts",
    title: "Monday Preview Posts",
    originalGoal: "Growth",
    whyBacklogged: "Routine but not growth driver. Doesn't convert, just maintains.",
    rating: "⭐⭐",
  },
  {
    id: "gamma-strike-rejection-posts",
    title: "Gamma Strike Rejection Posts",
    originalGoal: "Growth",
    whyBacklogged: "Situational. Can't force precision moments. Opportunistic only.",
    rating: "⭐⭐",
  },
  {
    id: "quote-tweet-news",
    title: "Quote Tweet the News",
    originalGoal: "Growth",
    whyBacklogged: "Everyone does this. Not differentiated. Low conversion.",
    rating: "⭐⭐",
  },
  {
    id: "hiro-alert-delay-system",
    title: "HIRO Alert Delay System",
    originalGoal: "Workflow",
    whyBacklogged: "Over-engineered. Just post manually with delay or use scheduling.",
    rating: "⭐⭐",
  },
  {
    id: "catalyst-calendar-visual",
    title: "Catalyst Calendar Visual",
    originalGoal: "Workflow",
    whyBacklogged: "Catalyst posts were cut from Goal 1. No need for generator.",
    rating: "⭐⭐",
  },
  {
    id: "ai-video-content-pipeline",
    title: "AI Video Content Pipeline",
    originalGoal: "Workflow",
    whyBacklogged: "High effort, unproven ROI. Cool idea but not MVP priority.",
    rating: "⭐⭐",
  },
  {
    id: "weekly-flow-digest-format",
    title: "Weekly Flow Digest Format",
    originalGoal: "Workflow",
    whyBacklogged: "Vague. What even is this? Not defined enough to build.",
    rating: "⭐",
  },
  {
    id: "tradingagents-review",
    title: "TradingAgents Review",
    originalGoal: "Platform",
    whyBacklogged: "Research project, not feature. Interesting but doesn't ship value.",
    rating: "⭐⭐",
  },
  {
    id: "education-hub-outline",
    title: "Education Hub Outline",
    originalGoal: "Platform",
    whyBacklogged: "Nice-to-have. New members need alerts working first, education second.",
    rating: "⭐⭐",
  },
  {
    id: "paper-trading-bot",
    title: "Paper Trading Bot",
    originalGoal: "Platform",
    whyBacklogged: "Complex build for marketing asset. Simpler ways to prove system works (accuracy page).",
    rating: "⭐⭐",
  },
  {
    id: "discord-knowledge-bot",
    title: "Discord Knowledge Bot",
    originalGoal: "Platform",
    whyBacklogged: "High effort. You don't have enough support volume to justify this yet.",
    rating: "⭐⭐",
  },
  {
    id: "gamma-explainer-series",
    title: "Gamma Explainer Series",
    originalGoal: "(Cut v2)",
    whyBacklogged: "High effort, low conversion",
    rating: "⭐⭐",
  },
  {
    id: "monthly-state-of-tsla",
    title: "Monthly State of TSLA",
    originalGoal: "(Cut v2)",
    whyBacklogged: "Not differentiated",
    rating: "⭐⭐",
  },
  {
    id: "hiro-swing-visualization",
    title: "HIRO Swing Visualization",
    originalGoal: "(Cut v2)",
    whyBacklogged: "Too niche",
    rating: "⭐⭐",
  },
  {
    id: "tradingview-table-export",
    title: "TradingView Table Export",
    originalGoal: "(Cut v2)",
    whyBacklogged: "Nice-to-have",
    rating: "⭐⭐",
  },
  {
    id: "qmd-local-search",
    title: "QMD Local Search",
    originalGoal: "(Cut v2)",
    whyBacklogged: "Internal tooling",
    rating: "⭐⭐",
  },
  {
    id: "export-claude-kb",
    title: "Export Claude KB",
    originalGoal: "(Cut v2)",
    whyBacklogged: "Maintenance task",
    rating: "⭐⭐",
  },
];

export const codexPriorities = [
  {
    id: 1,
    title: "Daily Mode Card Generator",
    enablesWhat: "Enables daily X presence",
  },
  {
    id: 2,
    title: "Accuracy Comparison Generator",
    enablesWhat: "Enables proof content",
  },
  {
    id: 3,
    title: "Report-to-Tweet Pipeline",
    enablesWhat: "Eliminates blank page problem",
  },
  {
    id: 4,
    title: "Weekly Report Template",
    enablesWhat: "Unblocks Sunday workflow",
  },
];
