export type BacklogStatus = "backlog" | "in-progress" | "done";
export type BacklogPriority = "P0" | "P1" | "P2";
export type BacklogCategory = "growth" | "workflow" | "platform";

export interface BacklogItem {
  id: string;
  priority: BacklogPriority;
  title: string;
  description: string;
  status: BacklogStatus;
  category: BacklogCategory;
  tags: string[];
  dateAdded: string;
  effort: "quick" | "medium" | "large";
  assessment: string;
  isNew?: boolean;
}

export const categories = {
  growth: {
    emoji: "🎯",
    title: "Grow Subscribers",
    description: "Convert X impressions → followers → email signups → paying members",
  },
  workflow: {
    emoji: "⚡",
    title: "Streamline Workflows",
    description: "Automate repetitive tasks → free up Justin's time for high-leverage work",
  },
  platform: {
    emoji: "🏗️",
    title: "Platform Excellence",
    description: "Flawless operations + features that create massive subscriber value",
  },
};

export const backlogItems: BacklogItem[] = [
  // ============ GOAL 1: GROW SUBSCRIBERS ============
  {
    id: "daily-mode-card",
    priority: "P0",
    title: "Daily Mode Card",
    description: "Branded image posted 7:45am CT daily with MODE, key levels, posture. Template-based, auto-generated from report data.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Automation", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "Compounds daily. Zero-effort once templated. Becomes ritual. Brand building 101.",
  },
  {
    id: "hiro-spike-alerts-delayed",
    priority: "P0",
    title: "HIRO Spike Alerts (Delayed)",
    description: "Post HIRO threshold alerts to X with 15-30 min delay. Creates FOMO, proves edge.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "FOMO", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "FOMO is the strongest conversion driver. 'Subscribers got this 30 min ago' = immediate value proof.",
  },
  {
    id: "base-case-accuracy-posts",
    priority: "P0",
    title: "Base Case Accuracy Posts",
    description: "Screenshot report predictions vs actual results. Builds credibility with proof.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Proof", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "Proof beats promises. Screenshot predictions vs results. Undeniable credibility.",
  },
  {
    id: "weekly-scorecard-thread",
    priority: "P0",
    title: "Weekly Scorecard Thread",
    description: "Friday/Saturday thread: predictions vs results, accuracy %, lessons. Accountability builds trust.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Transparency", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Radical transparency is RARE. Showing losses builds more trust than hiding them. Differentiator.",
  },
  {
    id: "free-daily-levels-email",
    priority: "P0",
    title: "Free Daily Levels Email (Lead Magnet)",
    description: "Exchange email for free daily key levels. Builds list. Nurtures to paid.",
    status: "backlog",
    category: "growth",
    tags: ["Email", "Lead Gen", "Funnel"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "MISSING FROM CURRENT STRATEGY. This is the funnel gap.",
    isNew: true,
  },
  {
    id: "why-it-moved-recaps",
    priority: "P1",
    title: '"Why It Moved" Recaps',
    description: 'After big moves (±3%), explain what happened with levels/HIRO. Educational authority.',
    status: "backlog",
    category: "growth",
    tags: ["Content", "Education", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Captures search traffic ('why did TSLA drop'). Positions as expert, not reactor. Evergreen.",
  },
  {
    id: "public-accuracy-dashboard",
    priority: "P1",
    title: "Public Accuracy Dashboard Link",
    description: "Every post links to flacko.ai/accuracy showing historical track record. Social proof at scale.",
    status: "backlog",
    category: "growth",
    tags: ["Website", "Proof", "Trust"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Don't trust me, check the numbers.",
    isNew: true,
  },
  {
    id: "pre-earnings-playbook",
    priority: "P1",
    title: "Pre-Earnings Playbook Posts",
    description: "3-5 days before ER: historical moves, gamma setup, scenarios. Peak attention.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Earnings", "X"],
    dateAdded: "2026-02-02",
    effort: "large",
    assessment: "Peak attention moments. Only 4x/year but MASSIVE reach. Worth the effort.",
  },
  {
    id: "what-would-you-do-polls",
    priority: "P1",
    title: '"What Would You Do?" Polls',
    description: "Engagement bait that educates. 'TSLA at $430, HIRO +800M. You: A) Buy B) Wait C) Sell'",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Engagement", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "Drives comments, shares framework.",
    isNew: true,
  },
  {
    id: "contrarian-call-accountability",
    priority: "P2",
    title: "Contrarian Call + Accountability",
    description: "High-conviction public calls with specific targets. Engagement + credibility if right.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Bold", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "High risk/reward. When right = viral. When wrong = own it = trust. Use sparingly.",
  },
  {
    id: "subscriber-testimonials",
    priority: "P2",
    title: "Subscriber Testimonial Highlights",
    description: "Screenshot subscriber wins. 'Member caught the $424 bounce using our levels.'",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Social Proof", "X"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "Real people, real results.",
    isNew: true,
  },
  {
    id: "loss-autopsy-posts",
    priority: "P2",
    title: "Loss Autopsy Posts",
    description: "When a call is WRONG, publicly break down why. Counter-intuitive but builds massive trust.",
    status: "backlog",
    category: "growth",
    tags: ["Content", "Transparency", "X"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Nobody does this.",
    isNew: true,
  },

  // ============ GOAL 2: STREAMLINE WORKFLOWS ============
  {
    id: "weekly-report-template",
    priority: "P0",
    title: "Weekly Report Template",
    description: "Create .md template for Sunday weekly workflow.",
    status: "done",
    category: "workflow",
    tags: ["Template", "Reports", "Blocking"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "BLOCKING. Can't do Sunday workflow without it. Immediate unblock.",
  },
  {
    id: "daily-mode-card-generator",
    priority: "P0",
    title: "Daily Mode Card Generator",
    description: "Input: report JSON → Output: branded PNG. Post in 30 seconds.",
    status: "in-progress",
    category: "workflow",
    tags: ["Automation", "Design", "Pipeline"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Enables #1 growth item.",
  },
  {
    id: "accuracy-comparison-generator",
    priority: "P0",
    title: "Accuracy Comparison Generator",
    description: "Input: predictions + actuals → Output: before/after image. Enables accuracy posts without manual work.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Design", "Pipeline"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Enables accuracy posts without manual work.",
  },
  {
    id: "report-to-tweet-pipeline",
    priority: "P1",
    title: "Report-to-Tweet Pipeline",
    description: "Auto-generate 3-5 tweet drafts from each daily report. Pick best, post. Eliminates blank page problem.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Content", "AI"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Eliminates blank page problem.",
    isNew: true,
  },
  {
    id: "auto-screenshot-scheduler",
    priority: "P1",
    title: "Auto-Screenshot Scheduler",
    description: "Capture TradingView/SpotGamma at market open, noon, close automatically. No manual intervention.",
    status: "done",
    category: "workflow",
    tags: ["Automation", "Screenshots", "Cron"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "No manual intervention.",
    isNew: true,
  },
  {
    id: "content-calendar-dashboard",
    priority: "P2",
    title: "Content Calendar Dashboard",
    description: "Visual calendar: what posts when. Never miss a scheduled post. See gaps. Plan ahead.",
    status: "backlog",
    category: "workflow",
    tags: ["Dashboard", "Planning", "Content"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Never miss a scheduled post.",
    isNew: true,
  },
  {
    id: "one-click-post-queue",
    priority: "P2",
    title: "One-Click Post Queue",
    description: "Approve → auto-posts to X/Discord. No copy-paste. No manual webhook calls.",
    status: "backlog",
    category: "workflow",
    tags: ["Automation", "Publishing", "UX"],
    dateAdded: "2026-02-02",
    effort: "large",
    assessment: "No copy-paste. No manual webhook calls.",
    isNew: true,
  },

  // ============ GOAL 3: PLATFORM EXCELLENCE ============
  {
    id: "email-notifications-backend",
    priority: "P0",
    title: "Email Notifications Backend",
    description: "Build backend for price alert email delivery. Member-requested feature.",
    status: "backlog",
    category: "platform",
    tags: ["Email", "Alerts", "Backend"],
    dateAdded: "2026-02-02",
    effort: "large",
    assessment: "Member-requested. Not everyone watches Discord. Direct delivery = direct value.",
  },
  {
    id: "alert-accuracy-tracking-auto",
    priority: "P0",
    title: "Alert Accuracy Tracking (Auto)",
    description: "System auto-tracks which price alerts hit. Display hit rate. Proves system works.",
    status: "backlog",
    category: "platform",
    tags: ["Analytics", "Alerts", "Trust"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Proves system works.",
    isNew: true,
  },
  {
    id: "public-accuracy-page",
    priority: "P0",
    title: "Public Accuracy Page",
    description: "flacko.ai/accuracy — historical track record anyone can verify. Marketing + transparency.",
    status: "backlog",
    category: "platform",
    tags: ["Website", "Trust", "Marketing"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "Marketing + transparency.",
    isNew: true,
  },
  {
    id: "discord-feedback-channel",
    priority: "P1",
    title: "Discord Feedback Channel",
    description: "Dedicated channel for member ideas. Trunks monitors, easy engagement win.",
    status: "done",
    category: "platform",
    tags: ["Discord", "Community", "Feedback"],
    dateAdded: "2026-02-02",
    effort: "quick",
    assessment: "10-minute setup. Immediate feedback loop. Know what subscribers actually want.",
  },
  {
    id: "mobile-push-notifications",
    priority: "P1",
    title: "Mobile Push Notifications",
    description: "Beyond email. Instant alerts to phone. Higher engagement than email.",
    status: "backlog",
    category: "platform",
    tags: ["Mobile", "Alerts", "Engagement"],
    dateAdded: "2026-02-02",
    effort: "large",
    assessment: "Higher engagement than email.",
    isNew: true,
  },
  {
    id: "member-performance-dashboard",
    priority: "P2",
    title: "Member Performance Dashboard",
    description: "Personalized: their alerts, which ones hit, their accuracy following the system.",
    status: "backlog",
    category: "platform",
    tags: ["Dashboard", "Personalization", "Analytics"],
    dateAdded: "2026-02-02",
    effort: "large",
    assessment: "Personalized value proof.",
    isNew: true,
  },
  {
    id: "spotgamma-data-expansion",
    priority: "P2",
    title: "SpotGamma Data Expansion",
    description: "Add Equity Hub levels, FlowPatrol insights to daily reports. More data = more value.",
    status: "in-progress",
    category: "platform",
    tags: ["Data", "Reports", "SpotGamma"],
    dateAdded: "2026-02-02",
    effort: "medium",
    assessment: "More data = more value.",
    isNew: true,
  },
];
